name: Ejemplo CI/CD 

on: [push]

jobs:
    inicio:
      runs-on: windows-latest
      #Pasos:
      steps:
        - name: mostrar texto
          run: echo "Paso para clonar el repositorio a github actions"
        - name: Clonar repositorio
          uses: actions/checkout@v4.2.2
    build:
      runs-on: windows-latest
      needs: [inicio]
      steps:
        - name: texto
          run: echo "Construir"
        - name: instalar PHP y composer
          run: |
            choco install php --version=8.1
            choco install composer
            php --v
            composer --version
        - name: instalar MySQL
          run: |
            choco install mysql --version=8.0
            mysql --version 
        
    test:
      runs-on: windows-latest
      needs: [build]
      steps:
        - name: texto
          run: echo "Construir"

    deploy:
      runs-on: windows-latest
      needs: [test]
      steps:
        - name: texto
          run: echo "Construir"